INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'vestir',34,'34','11');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'casual',23,'37','12');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'casual',23,'37','13');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'vestir',34,'34','14');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'casual',23,'37','15');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'casual',23,'37','16');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'casual',23,'37','17');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'casual',23,'37','18');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'casual',23,'37','19');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'casual',23,'37','20');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'vestir',34,'34','21');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'casual',23,'37','22');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'vestir',34,'34','23');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'casual',23,'37','24');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'vestir',34,'34','25');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'casual',23,'37','103');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'vestir',34,'34','178');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'casual',23,'37','136');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'vestir',34,'34','187');
INSERT INTO bavionline.blusa (idCliente, tipoBlusa, talla, color, idBlusa) VALUES (65,'casual',23,'37','138');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'98','E12','R12','T98');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'12','E13','R13','T99');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'13','E14','R14','T100');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'14','E15','R34','T101');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'45','E16','R35','T102');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'46','E17','R36','T103');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'49','E18','R37','T104');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'143','E19','R38','T105');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'145','E20','R39','T106');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'142','E21','R40','T107');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'155','E22','R41','T108');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'146','E23','R42','T109');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'1454','E24','R43','T110');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'124','E25','R44','T111');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'1232','E26','R45','T111');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'143','E27','R46','T111');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'234','E28','R47','T111');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'456','E29','R48','T111');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'567','E30','R49','T111');
INSERT INTO bavionline.categorias (idCliente, idVestido, idSudadera, idChamarra, idOficina) VALUES (65,'678','E31','R50','T111');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'larga',11,'negra','pana','ch38');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'larga',11,'negra','pana','ch38');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'larga',11,'negra','pana','ch38');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'larga',11,'negra','pana','ch38');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'larga',13,'34','pana','ch78');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'larga',11,'negra','pana','ch38');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.chamarra (idCliente, tipoChamarra, talla, color, textura, idChamarra) VALUES (65,'corta',11,'negra','pana','ch35');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa56','blu98','negro','of67');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');
INSERT INTO bavionline.oficina (idCliente, pantalon, blusa, sacos, idOficina) VALUES (65,'pa90','blu89','negro','of38');

INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'blanco','algodon','pa45');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'blanco','algodon','pa45');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'blanco','algodon','pa45');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'blanco','algodon','pa45');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'blanco','algodon','pa45');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'blanco','algodon','pa45');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');
INSERT INTO bavionline.pantalon (idCliente, talla, color, textura, idPantalon) VALUES (65,34,'negro','mezclilla','pa32');

INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'35','robusta','laura','perez','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'20','delada','Rebexa','flores','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'35','robusta','toña','guardes','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'20','delada','lola','buiytle','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'35','robusta','renata','guzman','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'20','delada','paula','luz','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'35','robusta','niurca','hernandez','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'20','delada','nicole','costes','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'35','robusta','oliudsa','ernipo','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'35','robusta','victor','contreras','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'20','delada','polisa','perez','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'35','robusta','eduardo','bioluda','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'20','delada','barbara','marquez','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'20','delada','dellana','marcos','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'35','robusta','corl','vivisa','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'35','robusta','zieda','buitres','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'20','delada','briadna','adelain','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'35','robusta','ñoile','contreras','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'20','delada','vivi','cortes','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'35','robusta','cortrin','lopez','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.perfil_usuario (idCliente, edad, complexion, nombre, apellido, ciudad, pais, direccion, email, telefono) VALUES (65,'35','robusta','alejandra','shantal','MEXICO','MEXICO','XXXXXX.GMAIL.COM','55678990');
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'chamarra','cafe','pana','fefemino','1800','50',32);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'Pantalon','negro','mezclilla','femenino','500','26',34);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'chamarra','cafe','pana','fefemino','1800','50',32);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'sudadera','37','algodon','femenino','600','190',28);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'chamarra','cafe','pana','fefemino','1800','50',32);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'Pantalon','negro','mezclilla','femenino','500','26',34);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'sudadera','37','algodon','femenino','600','190',28);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'chamarra','cafe','pana','fefemino','1800','50',32);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'sudadera','37','algodon','femenino','600','190',28);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'Pantalon','negro','mezclilla','femenino','500','26',34);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'sudadera','37','algodon','femenino','600','190',28);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'chamarra','cafe','pana','fefemino','1800','50',32);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'sudadera','37','algodon','femenino','600','190',28);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'sudadera','37','algodon','femenino','600','190',28);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'Pantalon','negro','mezclilla','femenino','500','26',34);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'chamarra','cafe','pana','fefemino','1800','50',32);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'sudadera','37','algodon','femenino','600','190',28);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'sudadera','37','algodon','femenino','600','190',28);
INSERT INTO bavionline.producto (idCliente, tipoProducto, color, textura, genero, precio, stock, talla) VALUES (65,'Pantalon','negro','mezclilla','femenino','500','26',34);
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,65,'34','larga','sud56');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,65,'34','larga','sud56');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,65,'34','larga','sud56');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,65,'34','larga','sud56');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.sudadera (idCliente, talla, color, tipoSudadera, idSudadera) VALUES (65,32,'37','corta','sud509');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','45',32,'34','larga','VES567');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','45',32,'34','larga','VES567');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','45',32,'34','larga','VES567');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','45',32,'34','larga','VES567');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
INSERT INTO bavionline.vestido (idCliente, casual, fiesta, talla, color, tipoManga, idVestido) VALUES (65,'32g','47',32,'37','corta','VES47');
